use tokio::sync::mpsc::UnboundedReceiver;
use tokio::sync::{broadcast, mpsc};

use shared::{
    BackpressureSignal, ConsensusEvent, EthSignedTx, OurCommittedSubDag, Round, TxBatch,
};

use crate::backpressure::BackpressureController;
use crate::pending_queue::{HardCommitDecision, PendingQueue};

/// Default pending-queue depth at which backpressure kicks in.
const DEFAULT_THRESHOLD: usize = 16;

/// First leader round in Mysticeti (wave 1 leader = round 3).
const FIRST_LEADER_ROUND: Round = 3;

/// Number of rounds per wave (leader spacing).
const WAVE_LENGTH: Round = 3;

/// Decision forwarded to the shadow-state / commit layer after a HardCommit.
#[derive(Debug, Clone)]
pub enum CommitDecision {
    /// Speculative execution (SoftCommit path) was correct; finalize it.
    Commit { commit_index: u64, round: Round },
    /// Speculative result must be discarded (e.g., leader skip in future work).
    Discard { commit_index: u64 },
    /// No speculative run existed; executor must run these txs now (final path).
    FreshBatch(TxBatch),
}

/// Asynchronous event loop that mediates between the consensus layer and the
/// EVM executor.
///
/// Responsibilities:
/// - Buffer out-of-order SoftCommits and dispatch them in round order.
/// - On HardCommit, either confirm a speculative result or supply a fresh batch.
/// - Respect backpressure signals from the executor (pause/resume dispatch).
/// - Emit outbound backpressure signals when the pending queue grows too deep.
pub struct PipelineScheduler {
    consensus_rx: broadcast::Receiver<ConsensusEvent>,
    executor_tx: mpsc::Sender<TxBatch>,
    backpressure_rx: mpsc::Receiver<BackpressureSignal>,
    backpressure: BackpressureController,
    pending: PendingQueue,
    commit_tx: mpsc::Sender<CommitDecision>,
}

impl PipelineScheduler {
    /// Construct a scheduler.
    ///
    /// Returns `(scheduler, bp_rx)` where `bp_rx` carries outbound backpressure
    /// signals generated by the scheduler when its pending queue exceeds the
    /// depth threshold.
    pub fn new(
        consensus_rx: broadcast::Receiver<ConsensusEvent>,
        executor_tx: mpsc::Sender<TxBatch>,
        backpressure_rx: mpsc::Receiver<BackpressureSignal>,
        commit_tx: mpsc::Sender<CommitDecision>,
    ) -> (Self, UnboundedReceiver<BackpressureSignal>) {
        let (bp_tx, bp_rx) = tokio::sync::mpsc::unbounded_channel();
        let scheduler = Self {
            consensus_rx,
            executor_tx,
            backpressure_rx,
            backpressure: BackpressureController::new(DEFAULT_THRESHOLD, bp_tx),
            pending: PendingQueue::new(FIRST_LEADER_ROUND, DEFAULT_THRESHOLD),
            commit_tx,
        };
        (scheduler, bp_rx)
    }

    /// Run the scheduler event loop until all input senders are dropped.
    pub async fn run(mut self) {
        loop {
            tokio::select! {
                result = self.consensus_rx.recv() => {
                    match result {
                        Ok(event) => self.handle_consensus_event(event).await,
                        Err(broadcast::error::RecvError::Lagged(n)) => {
                            tracing::warn!("consensus broadcast lagged by {} messages", n);
                            // Continue — partial miss, keep processing subsequent events
                        }
                        Err(broadcast::error::RecvError::Closed) => break,
                    }
                }
                signal = self.backpressure_rx.recv() => {
                    match signal {
                        Some(s) => self.backpressure.update(s),
                        None => break,
                    }
                }
            }
        }
    }

    async fn handle_consensus_event(&mut self, event: ConsensusEvent) {
        match event {
            ConsensusEvent::SoftCommit { round, txs, .. } => {
                self.handle_soft_commit(round, txs).await;
            }
            ConsensusEvent::HardCommit { subdag } => {
                self.handle_hard_commit(subdag).await;
            }
        }
    }

    async fn handle_soft_commit(&mut self, round: Round, txs: Vec<EthSignedTx>) {
        debug_assert!(round > 0, "round must be positive");
        self.pending.insert(round, txs);
        self.backpressure.check(self.pending.depth());
        if !self.backpressure.is_paused() {
            self.flush_pending().await;
        }
    }

    async fn handle_hard_commit(&mut self, subdag: OurCommittedSubDag) {
        let round = subdag.leader.round;
        let commit_index = subdag.commit_index;
        debug_assert!(round > 0, "leader round must be positive");
        debug_assert!(commit_index > 0, "commit_index must be positive");

        let decision = match self.pending.on_hard_commit(round, commit_index) {
            HardCommitDecision::Commit { commit_index, round } => {
                CommitDecision::Commit { commit_index, round }
            }
            HardCommitDecision::FreshExecution { round, commit_index } => {
                let txs: Vec<EthSignedTx> = subdag
                    .blocks
                    .iter()
                    .flat_map(|b| b.txs.iter().cloned())
                    .collect();
                CommitDecision::FreshBatch(TxBatch {
                    round,
                    commit_index,
                    txs,
                    is_optimistic: false,
                })
            }
        };

        // Ignore send errors: commit layer may have shut down already.
        let _ = self.commit_tx.send(decision).await;
    }

    /// Send all consecutive dispatchable entries to the executor in order.
    async fn flush_pending(&mut self) {
        for (round, txs) in self.pending.drain_dispatchable() {
            let batch = TxBatch {
                commit_index: round / WAVE_LENGTH, // wave index
                round,
                txs,
                is_optimistic: true,
            };
            // Ignore send errors: executor may have shut down.
            let _ = self.executor_tx.send(batch).await;
        }
        // Re-evaluate backpressure after the queue depth has changed.
        self.backpressure.check(self.pending.depth());
    }
}
